library(SWOMSE)

OM.root <- 'G:/My Drive/Projects/Projects_2020/ICCAT_Swordfish/OMs/Grid_2020'
OMbase.dir <-  file.path(OM.root, "Michael_March2020/NSWO_MSE_SS3_Base_v2")
OMgrid.dir <- file.path(OM.root, "grid_2020")
OMgrid.dirs <- list.dirs(OMgrid.dir, recursive = FALSE)

ord <- lapply(strsplit(OMgrid.dirs, 'iter'), '[[', 2) %>% as.numeric() %>% order()
OMgrid.dirs <- OMgrid.dirs[ord]

# RepList <- readRDS('OM_objects/RepList.rda')
# x <- RepList[[1]]

nsim = 48; proyears = 50; reps = 1; maxF = 3;
seed = 1; interval=1; Obs = MSEtool::Generic_Obs;
Imp = MSEtool::Perfect_Imp;
import_mov = TRUE; Name = "OM generated by SS2OM function";
Source = "No source provided"; Author = "No author provided";
Gen=1:2; AgeRec=1;

source("R/SWO_SS2OM.r")

replist <- r4ss::SS_output(OMgrid.dirs[245])

r4ss::SSplotSelex(replist)
r4ss::SSplotDiscard(replist)


x=replist; nsim=2; Obs=Perfect_Info;

OM <- SWO_SS2OM(replist, nsim=2, Obs=Perfect_Info)


OM@CAL_ESS <-OM@CAL_nsamp <- c(5000, 5000)

matplot(OM@cpars$CAL_binsmid, OM@cpars$SLarray[1,,], type="l",
        xlab="Length", ylab="Selectivity")


matplot(OM@cpars$CAL_binsmid, OM@cpars$retL[1,,], type="l")

Hist <- runMSE(OM, Hist=TRUE)


Years <- 1950:2017
sim <- 1
subYr <- 1970
yr <- match(subYr, Years)

CAL_mids <- Hist@Data@CAL_mids
CAL <- Hist@Data@CAL

SS_Length <- replist$lendbase %>% dplyr::filter(Yr %in% Years) %>%
  dplyr::group_by(Yr, Bin) %>% dplyr::summarise(Pred=sum(Exp))

SS_dat <- SS_Length %>% filter(Yr==subYr)
SS_dat$Pred <- SS_dat$Pred/sum(SS_dat$Pred) * sum(CAL[sim,yr,])
plot(CAL_mids, CAL[sim,yr,], type="b")
lines(SS_dat$Bin, SS_dat$Pred, col="blue")






# Selectivity
par(mfrow=c(2,2))
plot(0:OM@maxage, Hist@SampPars$V[1,,yr], type="b", ylim=c(0,1))
plot(0:OM@maxage, OM@cpars$Len_age[1,,yr], type="b", ylim=c(0,max(OM@cpars$Len_age)))

plot(Hist@Data@CAL_mids, OM@cpars$SLarray[sim,,yr], type='b', ylim=c(0,1))




### COMPARE OTHER SELECTIVITY PATTERN  #####

## Question to Resolve
# retention & selectivity curves


Compare_SS <- function(Hist, replist) {
  nyears <- length(Hist@TSdata$VB[1,])
  Years <- (Hist@OM$CurrentYr[1] - nyears + 1):Hist@OM$CurrentYr[1]

  # ---- Compare N-at-Age-1 ----
  # Unfished
  SS_age <- replist$natage_annual_1_no_fishery %>%
    dplyr::filter(Year %in% Years) %>%
    dplyr::group_by(Year) %>% dplyr::select(Year, Age='0') %>%
    dplyr::summarize(n=sum(Age))

  plot(SS_age, bty="n", ylab="N", main="N-at-age-1 Unfished")
  lines(SS_age$Year, Hist@AtAge$N_unfished[1,1,])

  # Fished
  SS_age <- replist$natage_annual_2_with_fishery %>%
    dplyr::filter(Year %in% Years) %>%
    dplyr::group_by(Year) %>% dplyr::select(Year, Age='0') %>%
    dplyr::summarize(n=sum(Age))

  plot(SS_age, bty="n", ylab="N", main="N-at-age-1 Fished", type="p", col='blue')
  lines(SS_age$Year, Hist@AtAge$Nage[1,1,])


  # ---- Compare Biomass ----
  SS_TS <- replist$timeseries %>% filter(Yr %in% Years)
  plot(SS_age$Year, Hist@TSdata$SSB[1,]/Hist@Ref$SSB0, type="l")
  lines(SS_age$Year, SS_TS$SpawnBio/replist$SBzero, lwd=2, col='blue')

  # ---- Compare Catch -----
  SS_Catch <- replist$catch %>% dplyr::filter(Yr %in% Years) %>%
    dplyr::group_by(Yr) %>% dplyr::summarise(Catch=sum(Obs))

  matplot(SS_Catch$Yr, t(Hist@TSdata$Catch), type="l")
  lines(SS_Catch$Yr, SS_Catch$Catch, col='blue')

  # ---- Compare Size Composition ----






  # at-age

  SS_age <- replist$natage %>%
    dplyr::filter(Yr %in% Years, `Beg/Mid` == "B") %>%
    dplyr::group_by(Yr) %>% dplyr::select(Age='0') %>%
    dplyr::summarize(n=sum(Age))

  plot(SS_age)
  lines(SS_age$Yr, Hist@AtAge$Nage[1,1,])


}

# compare n-at-age in first year they deviate - 1990
DF <- data.frame(SS_age, simN=Hist@AtAge$Nage[1,1,], Nrat=SS_age$n/Hist@AtAge$Nage[1,1,],
                 simDep= Hist@TSdata$SSB[1,]/Hist@Ref$SSB0, SSdep=SS_TS$SpawnBio/replist$SBzero)
DF$Deprat <- DF$SSdep/DF$simDep
DF %>% filter(Yr==1990)

# expected recruitment in 1990
plot(DF$n, type='l')
lines(rec * exp(-0.1), col='blue')


## -- Custom SS2OM function -- ##

fl <- tempfile()
fl
saveRDS(OM, fl)
Stock <- readRDS("C:\\Users\\Adrian\\AppData\\Local\\Temp\\RtmpA5Eyj8\\file1ab055124da6")
length(OM@M2)
