---
title: "North Atlantic Swordfish Operating Model Fitting Report"
subtitle: ""
author: "Adrian Hordyk"
date:  "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true 
    
---

```{r, echo=FALSE}
# OMinfo <- datList$OMinfo
# data <- datList$data
# likelihood <- datList$likelihood
# cpue <- datList$cpue
# SpRecDF <- datList$SpRecDF
```
# Operating Model Scenario

```{r, echo=FALSE, results="asis"}
  OMinfo <- SWOMSE::OMs_DF %>% dplyr::filter(n==OM.n)
  dt <- OMinfo[,1:7]
  rownames(dt) <- NULL
  colnames(dt) <- c("M", 'sigmaR', 'h', 'cpue_cv', 'CAL_ESS', 'Q increase', 'Env. Covariate')
  dt %>% knitr::kable() %>%
    kableExtra::kable_styling() 
```

# Fleet Information
```{r, echo=FALSE, results="asis"}
Fleet_DF %>% knitr::kable(format = "html", escape = F) %>%
  kableExtra::kable_styling("striped", full_width = T)

```

# Data Summary

```{r echo=FALSE, out.width ='100%'}
DataSummary <- Data_DF %>% dplyr::select(year, Code, Name, Catch, CPUE_Obs,
                                         Length.Comp, Mean.Weight) %>%
  tidyr::pivot_longer(cols=c('Catch', 'CPUE_Obs', 'Length.Comp', 'Mean.Weight'),
                      names_to = 'Data') %>%
  dplyr::mutate(is.data=ifelse(value>0, TRUE, NA)) %>%
  na.omit()

Data.Names <- c("Catch", 'CPUE', "Length Composition", "Mean Weight")
DataSummary$Data <- factor(DataSummary$Data, labels=Data.Names)

ggplot2::ggplot(DataSummary, ggplot2::aes(year, Code, color=is.data)) +
  ggplot2::facet_wrap(~Data, ncol=2) +
  ggplot2::geom_line(size=2) +
  ggplot2::labs(y="Fleet", x="Year", color='') +
  ggplot2::scale_color_manual(values='#357DE9') +
  ggplot2::theme_bw()+
  ggplot2::guides(color="none") +
  ggplot2::scale_x_date(breaks=seq.Date(min(AllDat$year2), max(AllDat$year2), "5 year"),
               labels = scales::date_format("%Y")) +
  ggplot2::theme(axis.text.x= ggplot2::element_text(angle=45, hjust=1),
        strip.background = ggplot2::element_blank(),
        strip.text = ggplot2::element_text(size=12))
 
```


# Objective Function Values

```{r, echo=FALSE, results="asis"}
likelihood <- Like_List[[OM.n]]
dt <- likelihood[[1]][1,]
rownames(dt) <- NULL
dt %>% t() %>% knitr::kable(format = "html", escape = F) %>%
  kableExtra::kable_styling("striped", full_width = F)

```

```{r, echo=FALSE, results="asis"}
dt <- likelihood[[2]][!grepl("lambda", likelihood[[2]]$Label),]
rownames(dt) <- NULL
dt %>% t() %>% knitr::kable(format = "html", escape = F) %>%
  kableExtra::kable_styling("striped", full_width = T)
```

# Fits to CPUE Indices

```{r, echo=FALSE}
# CPUE fitting info
cpue <- left_join(CPUE_List[[OM.n]], Fleet_DF, by='index')
cpue <- cpue %>% dplyr::group_by(Code) %>% dplyr::group_modify(~fit.diagnostics(.x))


# table of fit statistics
dt <- cpue %>% dplyr::ungroup() %>% dplyr::distinct(index, Fleet=Name, sd, cor, ac, rmse, mean.runs) %>%
  mutate_if(is.numeric, round, 2)
dt %>% DT::datatable(class = 'cell-border stripe', rownames = FALSE,
                     colnames = c('index', 'Fleet', 'Standard Deviation',
                                  'Correlation',
                                  'Auto-Correlation', 
                                  'Root Mean Squared Error',
                                  'Mean Runs'),
                     options = list(pageLength = nrow(dt), dom = 'tip'))

```


```{r, echo=FALSE, fig.width=8, fig.height=18}
cpue.plot(cpue)
```


# Spawning Biomass

```{r, echo=FALSE, fig.width=8, fig.height=6}
TSbio_dat <- TSBio_List[[OM.n]]
years <- min(TSbio_dat$year):TSbio_dat$year[which(TSbio_dat$Depletion == TSbio_dat$SS_Depletion)]
SSB_DF <- TSbio_dat %>% filter(year %in% years)

ggplot2::ggplot(SSB_DF, ggplot2::aes(x=year, y=SSB)) + ggplot2::geom_line(size=1.2) +
  ggplot2::expand_limits(y=c(0, 0)) +
  ggplot2::geom_line(ggplot2::aes(x=year, y=SB0), linetype=2) +
  ggplot2::scale_y_continuous(sec.axis = ggplot2::sec_axis(~ . /SSB_DF$SB0[1], name="Depletion",
                                         breaks=seq(0, 1, by=0.2)),
                              expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2::scale_x_continuous(breaks=seq(min(SSB_DF$year), max(SSB_DF$year), by=5)) +
  ggplot2::theme_bw() +
  ggplot2::labs(x="Year", y="Spawning Stock Biomass")
```


# Recruitment

```{r, echo=FALSE, fig.width=8, fig.height=6}
ggplot2::ggplot(SSB_DF, ggplot2::aes(x=year, y=Obs_Rec)) + ggplot2::geom_line(size=1.2) +
  ggplot2::expand_limits(y=c(0, 0)) +
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05)),
                              sec.axis = ggplot2::sec_axis(~ . /SSB_DF$R0[1], name="Relative Recruitment",
                                                           breaks=seq(0, 1, by=0.2))) +
  ggplot2::geom_line(ggplot2::aes(x=year, y=R0), linetype=2) +
  ggplot2::theme_bw() +
  ggplot2::labs(y="Recruits", x="Year") +
  ggplot2::scale_x_continuous(breaks=seq(min(SSB_DF$year), max(SSB_DF$year), by=5))
```


```{r, echo=FALSE, fig.width=8, fig.height=6}
SSB <- seq(0, 1, length.out = 100)
Rec <- (0.8  * OMs_DF[OM.n,]$h * SSB)/(0.2 * (1 - OMs_DF[OM.n,]$h) + (OMs_DF[OM.n,]$h - 0.2) * SSB) # BH SRR
srr <- data.frame(SSB=SSB*SSB_DF$SB0[1], Rec=Rec*SSB_DF$R0[1])

ggplot2::ggplot(SSB_DF, ggplot2::aes(x=SSB)) + 
  ggplot2::geom_point(size=2, ggplot2::aes(y=Obs_Rec)) +
  ggplot2::expand_limits(y=c(0, 0), x=0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2:: scale_x_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2::geom_line(data=srr, ggplot2::aes(x=SSB, y=Rec), color='blue', size=1.05) +
  ggplot2::theme_bw() +
  ggplot2::labs(y="Recruits", x="Spawning Stock Biomass") +
  ggplot2::geom_text(data=data.frame(x=0, y=Inf, text=paste0('h = ',  OMs_DF[OM.n,]$h)),
                     ggplot2::aes(x=x, y=y, label=text, hjust=-1, vjust=2))
```

```{r, echo=FALSE, fig.width=8, fig.height=6}
ggplot2::ggplot(SSB_DF, ggplot2::aes(x=SSB)) + 
  ggplot2::geom_text(ggplot2::aes(y=Obs_Rec, label=year, color=as.factor(year))) +
  ggplot2::expand_limits(y=c(0, 0), x=0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2:: scale_x_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2::geom_line(data=srr, ggplot2::aes(x=SSB, y=Rec), color='blue', size=1.05) +
  ggplot2::theme_bw() +
  ggplot2::guides(color=FALSE) +
  ggplot2::labs(y="Recruits", x="Spawning Stock Biomass") +
  ggplot2::geom_text(data=data.frame(x=0, y=Inf, text=paste0('h = ',  OMs_DF[OM.n,]$h)),
                     ggplot2::aes(x=x, y=y, label=text, hjust=-1, vjust=2))
```


```{r, echo=FALSE, fig.width=8, fig.height=6}
recdevs.plot(SSB_DF)
```




# Reference Points
```{r, echo=FALSE}
ref_points <- RefPoint_DF %>% dplyr::filter(n==OM.n) %>% dplyr::select(!n)

ref_points %>% knitr::kable(format = "html", escape = F) %>%
  kableExtra::kable_styling("striped", full_width = T)
```

# Kobe Plot 
```{r, echo=FALSE, fig.width=8, fig.height=6}
col1 <- 'yellow'
col2 <- 'green'
col3 <- 'red'
maxX <- max(2,max(SSB_DF$B.Bmsy))
maxY <- max(2,max(SSB_DF$F.Fmsy))

fill.df <- data.frame(x=c(0,0,1,1,
                          1,maxX, maxX, 1,
                          0,0,1,1,
                          1,maxX,maxX,1),
                      y=c(0,1,1,0,
                          0,0,1,1,
                          1,maxY, maxY, 1,
                          1,1, maxY, maxY),
                      group=c(rep('BL', 4),
                              rep('BR', 4),
                              rep('TL', 4),
                              rep('TR', 4)))

ind <- seq(1, nrow(SSB_DF), by=5)
labeldata <- SSB_DF[ind,]
ggplot(SSB_DF) +
  expand_limits(x=c(0,2), y=c(0,2)) +
  geom_polygon(data=fill.df, aes(x=x, y=y, fill=group), alpha=0.5) +
  geom_point(aes(x=B.Bmsy, y=F.Fmsy), size=2) +
  geom_line(aes(x=B.Bmsy, y=F.Fmsy)) +
  ggrepel::geom_text_repel(data=labeldata, aes(x=B.Bmsy, y=F.Fmsy, label=year
                                               )) + 
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0.01, 0.01))) +
  ggplot2:: scale_x_continuous(expand = ggplot2::expand_scale(mult=c(0.01, 0.01))) +
  theme_classic() +
  scale_fill_manual(values=c(col1, col2, col3, col1)) +
  labs(x="SB/SBMSY", y="F/FMSY") + 
  guides(color=FALSE, fill=FALSE)
```

# Selectivity
```{r, echo=FALSE, fig.width=8, fig.height=6}
SelectDat <- Select_List[[OM.n]]

ggplot2::ggplot(SelectDat, ggplot2::aes(x=Length.Class, y=Select, color=Name)) +
  ggplot2::geom_line(size=1) +
  ggplot2::expand_limits(y=c(0, 0), x=0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2:: scale_x_continuous(expand = ggplot2::expand_scale(mult=c(0, 0.05))) +
  ggplot2::theme_bw() +
  ggplot2::scale_color_discrete() +
  ggplot2::labs(x="Length Class (mm)", y="Selectivity", color="Fleet")
```

# Fits to Catch Data
```{r, echo=FALSE, fig.width=8, fig.height=6}
CatchDat <-  Catch_List[[OM.n]] %>% dplyr::filter(Obs>0)

ggplot(CatchDat, aes(x=year)) +
  facet_wrap(~Name) +
  geom_point(aes(y=Obs)) +
  geom_line(aes(y=Exp)) +
  theme_bw() +
  ggplot2::scale_y_continuous(expand = ggplot2::expand_scale(mult=c(0.01, 0.05))) +
  ggplot2::scale_x_continuous(expand = ggplot2::expand_scale(mult=c(0.01, 0.05))) +
  expand_limits(y=0) +
  theme(strip.background = element_blank()) +
  labs(x="Year", y="Catch")
  
```

# Fits to Length Composition Data




