% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Specifications for MSE Trials for North Atlantic Swordfish},
  pdfauthor={Adrian Hordyk adrian@bluematterscience.com},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={blue},
  pdfcreator={LaTeX via pandoc}}

\title{Specifications for MSE Trials for North Atlantic Swordfish}
\author{Adrian Hordyk \href{mailto:adrian@bluematterscience.com}{\nolinkurl{adrian@bluematterscience.com}}}
\date{11 September, 2023}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

The North Atlantic swordfish fishery, under the management of the \href{https://www.iccat.int/en/index.asp}{International Commission for the Conservation of Atlantic Tuna} (ICCAT), is undergoing a management strategy evaluation (MSE) process.

ICCAT describes \href{https://www.iccat.int/mse/en/index.asp}{MSE} as:

\begin{quote}
a collaborative process between Scientists and decision-makers that involves using computer simulation to compare the relative ability to achieve a set of management objectives using alternative Management Strategies, defined as different combinations of data collection schemes, methods of analysis, harvest control rules and subsequent processes leading to management actions.
\end{quote}

There are three main components in an MSE process:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Operating models (OMs)}: a collection of mathematical/statistical models that describe alternative hypotheses of the historical fishery dynamics and specifications for simulating the collection of data and implementation of management measures in the future;
\item
  \textbf{Candidate management procedures (CMPs)}: a set of proposed algorithms that generate management recommendations from fishery data, and will be evaluated in the MSE;
\item
  \textbf{Performance metrics (PMs)}: statistics use the quantitatively evaluate the CMPs against specified management objectives.
\end{enumerate}

The operating models, candidate management procedures, and performance metrics are developed as a collaborative effort between scientists, decision-makers, and other stakeholders in the fishery.

\hypertarget{about-this-document}{%
\subsection{About this document}\label{about-this-document}}

This document describes the specifications for the OMs, CMPs, and PMs that have been proposed and developed for the North Atlantic swordfish (hereafter swordfish) fishery.

It is a living document and will be continued to be updated so that it reflects the current state of the swordfish MSE process.

Members of the Swordfish Species Group (hereafter the Group) are encouraged to provide feedback, comments, or edits to any part of this document.

The document is written using the \href{https://www.markdownguide.org/}{Markdown} format and can edited in any text editor. The source document is available on the \href{https://github.com/ICCAT/nswo-mse/blob/master/docs/TS/Trial_Specs.Rmd}{ICCAT/nswo-mse} GitHub repository.

Group members can make edits to the document either \href{https://github.com/ICCAT/nswo-mse/edit/master/docs/TS/Trial_Specs.Rmd}{directly in the online repository} or by cloning the repository and submitting \href{https://github.com/ICCAT/nswo-mse/pulls}{pull requests} with their edits. Alternatively, they can email questions or comments to \href{mailto:adrian@bluematterscience.com}{Adrian}. The former approach has the advantage that all comments, questions, and edits are immediately visible to all members of the Group.

Group members can also use the \href{https://github.com/ICCAT/nswo-mse/discussions}{Discussions} feature on the Github repository to post questions, comments, or points for discussion related to any aspect of this document or the MSE process in general.

This document is available at the North Atlantic Swordfish MSE \href{https://iccat.github.io/nswo-mse/}{homepage}.

\hypertarget{mse-framework}{%
\section{MSE Framework}\label{mse-framework}}

The \texttt{SWOMSE} R package has been developed to conduct the MSE for the Atlantic swordfish fishery. All code used for the MSE is open-source and reproducible. Group members can install the package and reproduce the analysis on their own machines.

The \texttt{SWOMSE} package used for the swordfish MSE uses the \texttt{openMSE} framework. The \texttt{openMSE} package is automatically installed when \texttt{SWOMSE} is installed, and all \texttt{openMSE} functions are available to the user when the \texttt{SWOMSE} package is loaded.

\texttt{openMSE} is an R package that has been developed for conducting fast, flexible, and transparent, MSE for a wide range of fisheries. \texttt{openMSE} is an umbrella package that includes the \texttt{MSEtool}, \texttt{SAMtool} and \texttt{DLMtool} packages. A non-technical description of \texttt{openMSE} and its key features is available on the \href{https://openmse.com/}{\texttt{openMSE} website}.

The operating model in \texttt{openMSE}, including assumptions and equations, is described in detail in Carruthers \& Hordyk (2018).

The \href{../UserManual/User_Manual.html}{\texttt{SWOMSE} User Manual} includes instructions for installing the \texttt{SWOMSE} package and running the MSE analyses.

\hypertarget{stock-assessment}{%
\section{Stock Assessment}\label{stock-assessment}}

Previously, the swordfish operating models were based on the 2017 stock assessment (Anon., 2017) using Stock Synthesis 3 (SS3, Methot \& Wetzel, 2013).

A new stock assessment was conducted in 2022. The swordfish operating models have been updated based on this new assessment.

The report for the 2022 stock assessment is published in \href{https://www.iccat.int/Documents/CVSP/CV079_2022/n_2/CV079020392.pdf}{SCRS/2022/012}. Details of the 2022 assessment are published in \href{../SCRS_Papers/Schirripa_SCRS_2022_124.pdf}{SCRS/2022/124}. The data used in the 2022 assessment, and the structure and assumptions of the assessment model are summarized in the sub-sections below.

\hypertarget{data}{%
\subsection{Data}\label{data}}

The assessment used landings data from 8 longline fleets (7 national fleets and `Other' representing all catches not accounted for in the national fleets) (Table \ref{tab:fleet-info} and Figure \ref{fig:data-fig}).

There were 6 indices of abundance derived from catch-per-unit-effort (CPUE) data from the national fleets (Table \ref{tab:fleet-info} and Figure \ref{fig:data-fig}). Data from the Japan longline fleet was split into two phases: Early (1950 - 1993), and Late (1994 - 2020) due to changes in fishing practices in these periods. Similarly, the Chinese-Taipei longline fleet was split into two phases: Early (1968 - 1989) and Late (1997 - 2020). Five additional survey indices were developed from the age-specific (ages estimated from length data) CPUE from the Spain longline fleet (Table \ref{tab:fleet-info} and Figure \ref{fig:data-fig}).

Length composition data from 7 national longline fleets (Spain, U.S., Canada, Japan (Early, Late), Portugal, Chinese-Tapai (Early, Late), and Morocco) and the Canada/USA harpoon fleet (Figure \ref{fig:data-fig}). Mean weight data from two fleets (U.S. and Canada) were also used (Figure \ref{fig:data-fig}).

The catchability coefficient (\emph{q}) for the CPUE indices for Canada, Morocco, and the Age-1, Age-2, and Age-4 Spain age-specific survey indices, was made a function of the Atlantic Multidecadal Oscillation (AMO) (see \href{../SCRS_Papers/Schirripa_SCRS_2022_124.pdf}{SCRS/2022/124} for details).

The effective sample size (ESS) for the length composition data was established by adjusting ESS until unity was reached between modeled ESS and the Francis suggested sample size (See Anon., 2017 for details).

\begin{table}

\caption{\label{tab:fleet-info}Summary table of the fishing fleets and indices of abundances included the 2022 stock assessment of North Atlantic swordfish.}
\centering
\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X}
\toprule
Name & Code\\
\midrule
EU Spain longline (LL) & SPN 1\\
USA LL & US 2\\
Canada LL & CAN 3\\
Japan LL   Early & JPN ERLY 4\\
Japan LL   Late & JPN LATE 5\\
\addlinespace
EU Portugal LL & PORT 6\\
Chinese Taipai LL   Early & CHT EARLY 7\\
Chinese Taipai LL   Late & CHT LATE 8\\
Morocco LL & MOR 9\\
Canada USA Harpoon & HRPN 10\\
\addlinespace
Other   LL by the other CPCs, and all other gears except HP & OTH 11\\
USA Survey & US Survey 12\\
EU Portugal Survey & PORT Survey 13\\
Age 1 Survey & Age 1\\
Age 2 Survey & Age 2\\
\addlinespace
Age 3 Survey & Age 3\\
Age 4 Survey & Age 4\\
Age 5 plus Survey & Age 5 plus\\
\bottomrule
\end{tabu}
\end{table}

\begin{figure}
\includegraphics[width=400px]{../../img/Data_overview} \caption{Summary of the data used in the 2022 stock assessment.}\label{fig:data-fig}
\end{figure}

\hypertarget{model-structure}{%
\subsection{Model Structure}\label{model-structure}}

The SS3 model used one season, one area, and two sexes.

\hypertarget{fixed-biological-parameters}{%
\subsection{Fixed Biological Parameters}\label{fixed-biological-parameters}}

Natural mortality for both male and female was fixed at 0.2 for all age classes. Maturity-at-age was knife-edge, with 50\% at age-5 and 100\% thereafter. Fecundity was proportional to body weight. The growth parameters for the 2022 assessment were fixed at same used in the 2017 assessment, which were developed during the 2017 ICCAT Swordfish Data Preparatory Meeting (See Anon., 2017 for details).

\hypertarget{selectivity}{%
\subsection{Selectivity}\label{selectivity}}

Selectivity was modeled as a function of length. Dome-shaped selectivity was allowed for five fleets: EU-Spain, USA, Japan, EU-Portugal, and Morocco. Asymptotic selectivity was assumed for Canada, Chinese-Taipei and Other. The age-specific survey CPUEs were modeled with a fixed age-based selectivity.

\hypertarget{retention}{%
\subsection{Retention and Discard Mortality}\label{retention}}

The 2022 assessment assumed a minimum legal length of 119 cm lower jaw fork length (LFFL) for all fleets from 1993 - 2020, and estimated the selectivity and retention curves from the available data. Discard mortality was either estimated from the observer data (USA and Canada) or fixed at values taken from the literature (see SCRS/2022/124).

\hypertarget{stock-recruitment}{%
\subsection{Stock-Recruitment}\label{stock-recruitment}}

Expected recruitment to age-0 was calculated from the total spawning stock biomass using the Beverton-Holt stock-recruit function. The standard error for the log-normally distributed recruitment deviations (sigmaR) was fixed to 0.2. Steepness (\emph{h}) was fixed at the value estimated in the 2017 assessment (0.88).

\hypertarget{om-conditioning}{%
\section{Overview of Operating Model Conditioning}\label{om-conditioning}}

The 2022 stock assessment was used as the Base Case model for developing the operating models (OMs) evaluated in the MSE.

\hypertarget{om-uncertainty-grid}{%
\subsection{OM Uncertainty Grid}\label{om-uncertainty-grid}}

In 2019, the Swordfish Species Group developed an OM uncertainty grid using a full factorial design with 6 axes of uncertainty:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Natural mortality (\emph{M}) - three levels: 0.1, 0.2, 0.3
\item
  Recruitment variability (sigmaR; \(\sigma_R\)) - two levels: 0.2, 0.6
\item
  Steepness (\emph{h}) - three levels: 0.6, 0.75, 0.90
\item
  CPUE Lambda - three levels: 0.05, 1, 20
\item
  Directional trend in catchability (llq) - two levels: TRUE, FALSE
\item
  Environmental covariate (env) - two levels: TRUE, FALSE
\end{enumerate}

The directional increase in catchability was modeled by assuming a 1\% average annual increase in catchability throughout the history of the fishery, and adjusting the CPUE indices accordingly.

The environmental covariate was included by modeling catchability as a function of the AMO, as was done in the 2017 and 2022 stock assessments.

This factorial design of the 6 axes of uncertainty, each with 2 or 3 levels, resulted in an uncertainty grid of 216 OMs.

\hypertarget{evaluation-of-the-om-grid}{%
\subsection{Evaluation of the OM Grid}\label{evaluation-of-the-om-grid}}

Previous analyses of the OM uncertainty grid based on the 2017 assessment revealed that the three levels of natural mortality and steepness had the largest impact on the predicted stock dynamics \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_et_al_SCRS_2021_099.pdf}{Hordyk et al., 2021} and are therefore the most important axes of uncertainty in the OM grid.

The second level of recruitment variability (\(\sigma_R = 0.6\)) had a minor impact on the predicted stock dynamics \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_et_al_SCRS_2021_099.pdf}{Hordyk et al., 2021}, but did influence the relative performance of candidate management procedures \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_SCRS_2021_161.pdf}{Hordyk, 2021}. This second level is now treated as a robustness test (see below for more details).

The fourth axis of uncertainty was intended to evaluate the effect of alternative relative weightings of the length composition data and the indices of abundance. The three levels reflect a complete down-weighting of the indices of abundance (0.05; effectively only fitting the model to the length composition data), leaving the relative weighting of the two data sources unchanged from that used in the assessment (1), and up-weighting the indices of abundance so the model ignores the length composition data (20). This was done because of apparent conflicting signals between the length composition data and some of the indices of abundance, and the high computation demand of conducting the recommended iterative re-weighting procedure across all OMs in the grid (Francis, 2011). However, this iterative re-weighting procedure has now been conducted for the new operating models based on the 2022 assessment, and therefore this axis of uncertainty has been modified to two levels: 1) fit the assessment to both length and CPUE data and conduct the iterative re-weighting procedure, and 2) only fit the model to the CPUE data. This second level is now treated as a robustness test (see below for more details).

The fifth axis of uncertainty with the assumed 1\% increase in catchability for the indices of abundance had a relatively minor influence on both the predicted stock dynamics \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_et_al_SCRS_2021_099.pdf}{Hordyk et al., 2021} and the performance of candidate management procedures \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_SCRS_2021_161.pdf}{Hordyk, 2021}. Therefore it was decided that the default assumption for the operating models was to use the same indices as were used in the 2022 stock assessment; .e., the indices were not adjusted for an assumed 1\% annual increase in changeability. The second level of this axis, where the indices are adjusted for an assumed increase in catchability, is now treated as a robustness test (see below for more details).

In both the 2017 and 2022 stock assessments, the catchability coefficient (\emph{q}) for the CPUE indices for Canada, Japan, Portugal, Morocco, and the Spain age-specific survey indices, was made a function of the Atlantic Multidecadal Oscillation (AMO). Including this environmental covariate resulted in a better statistical fit to the data for these indices. The sixth axis of uncertainty examined the impact of not including this environmental covariate in the stock assessment. The analyses revealed that removing the environmental covariate from the assessment model had no detectable influence on either the predicted stock dynamics \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_et_al_SCRS_2021_099.pdf}{Hordyk et al., 2021} or the performance of candidate management procedures \href{https://iccat.github.io/nswo-mse/SCRS_Papers//Hordyk_SCRS_2021_161.pdf}{Hordyk, 2021}. Therefore, the environmental covariate was included in all models in the OM grid. Further examination of the impact of changing environmental conditions on the performance of the candidate management procedures may be examined in additional robustness tests (see below for more details).

This same pattern in results was found when the analyses were re-conducted with the new OM grid based on the 2022 assessment.

\hypertarget{operating-models}{%
\section{Operating Models}\label{operating-models}}

The OMs, conditioned using SS3, were imported into MSE framework using the \texttt{SS2MOM} function in \texttt{MSEtool} (see \href{https://msetool.openmse.com/reference/SS2MOM.html}{here} for details on the function).

Previously, the 2-sex SS3 models were imported into a combined single-sex operating model in the MSE framework. The MSE framework was updated in 2022, and the imported operating models now maintain the separate sexes in the same manner as the SS3 assessment. Since the fishery is managed with a single overall total allowable catch (TAC), the individual fishing fleets were aggregated together in the operating models.

The 2-sex operating model are available in the \texttt{SWOMSE} package as objects of class \texttt{MOM} (multi-stock operating model). For example, the 2022 stock assessment is available as the base case operating model named \texttt{MOM\_000}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(SWOMSE)}
\NormalTok{MOM\_000}\SpecialCharTok{@}\NormalTok{Name}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "M:0.2 sigmaR:0.2 steepness:0.88 Include CAL:TRUE llq:1 env:1 Class:Base Case"
\end{verbatim}

The operating models have been classified into two categories: Reference OMs and Robustness OMs. Table \ref{tab:OM-Description} provides a general overview of the operating models includes in the MSE analysis. The following sub-sections describe the Reference and Robustness OMs in more detail.

\begin{table}

\caption{\label{tab:OM-Description}Summary of the Base Case, Reference, and Robustness Operating Models.}
\centering
\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X}
\toprule
Class & Description\\
\midrule
Base Case & The 2022 Stock Assessment, considered the Base Case OM\\
Reference & Nine models spanning the key plausible uncertainties in natural mortality (M) and steepness of the Beverton-Holt stock-recruit relationship (h). Same as Base Case with 3 levels of M (0.1, 0.2, 0.3) and 3 levels of h (0.69, 0.80, 0.88)\\
R0 & Reference OM for the Robustness Tests. OM 5 of the Reference Set\\
R1 & Evaluate impact of an assumed 1 percent annual increase catchability, that is not accounted for in the standardization of the indices of abundance (historical and projection)\\
R2 & Same as R2, but only for the historical period\\
\addlinespace
R3a & Evaluate impact of cyclical pattern in recruitment deviations in projection period; a proxy for impact of climate change on stock productivity\\
R3b & Evaluate impact of lower than expected recruitment deviations for first 15 years of projection period; a proxy for impact of climate change on stock productivity\\
R4 & Evaluate impact of illegal, unreported, or unregulated catches\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{base-case}{%
\subsection{Base Case}\label{base-case}}

The Base Case operating model is the 2022 Stock Assessment. See the \protect\hyperlink{stock-assessment}{Stock Assessment section} for more details.

\hypertarget{reference_models}{%
\subsection{Reference Operating Models}\label{reference_models}}

The Reference OMs are based on the Base Case Model and span the plausible range for the key uncertainties. The Candidate Management Procedures (CMPs) are tuned across the Reference OMs (see the \protect\hyperlink{tuning}{CMP Tuning section} for more details.

Based on the analyses described \protect\hyperlink{om-conditioning}{above}, a set of 9 operating models were identified as the Reference OMs. These operating models spanned the three levels of \emph{M} (0.1, 0.2, and 0.3) and three levels \emph{h} (0.69, 0.80, and 0.88).

The values for steepness in the Reference Set were determined at the 2023 Intersessional Meeting of the Swordfish Working Group. The lower and upper values were set at the 95\% confidence intervals of a prior distribution for the steepness parameter used in the 2022 assessment.

The center value was calculated by first converting steepness to the Goodyear compensation ratio (CR) with \(\text{CR}=\frac{4h}{1-h}\). Using this equation, the CR for h = 0.69 and h = 0.88 are 8.90 and 29.33 respectively. A mid-point between these two CR values is calculated as:

\(\text{CR}_\text{mid} = e^{\frac{\sum_i\log\text{CR}_i}{2}}=16.16\), where the lower and upper values are 16.16/1.815 and 16.16 x 1.815 respectively. Back-calculating to steepness with \(h=\frac{\text{CR}}{\text{CR}+4}\) gives \(h=0.80\).

Initially the OMs with the lower steepness value \((h=0.6)\) was also considered to be in the Reference OMs. However, recent analysis and discussion with the MSE Technical Team has revealed that a such a low steepness is unlikely for North Atlantic swordfish. Consequently, the OMs with \(h=0.6\) have been re-classified into a Robustness Set.

The Reference OMs had the following assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Following the assessment, \(\sigma_R = 0.2\)
\item
  The Francis iterative re-weighting procedure was conducted on each operating model to find the appropriate weighting between the length compostion data and the indices of abundance
\item
  The standardized indices of abundance were used (i.e., no assumed 1\% increase in catchability)
\end{enumerate}

\hypertarget{r0.-reference-model}{%
\subsection{R0. Reference Model}\label{r0.-reference-model}}

The robustness tests are conducted for a single operating model from center of the Reference Set (M=0.2, h=0.8). R0 describes the performance of the CMPs for this single operating model, and is used for evaluating the results of the other robustness tests.

\hypertarget{r1.-hyperstable-indices-in-historical-and-projection-periods}{%
\subsection{R1. Hyperstable Indices in Historical and Projection Periods}\label{r1.-hyperstable-indices-in-historical-and-projection-periods}}

The R1 Robustness test evaluates the impact of a consistent increase in catchability that is not accounted for in the standardization of the indices, resulting in a hyper-stable index.

This test is implemented by assuming that the indices used in the OM conditioning were `corrected' for an average 1\% annual increase in catchability. This was done by decreasing the observed values of the indices by 1\% per year. Figure \ref{fig:r1-compare} shows the estimated F/FMSY and SB/SBMSY for the Reference model (R0) and the this robustness test (R1).

\begin{figure}
\includegraphics[width=400px]{../../img/R1_Increasing_q/Compare} \caption{The fishing mortality and spawning biomass relative to MSY reference points for R0 (reference OM) and R1, the robustness test that assumed the indices were corrected for an assumed 1 percent annual increase in catchability.}\label{fig:r1-compare}
\end{figure}

The MPs were provided with the observed historical indices (rather than the `corrected' indices). The unaccounted 1\% annual increase in catchability was assumed to continue in the projection period. This was done by assuming 1\% annual positive observation error for the indices in the projection period (Figure \ref{fig:r1-index}).

\begin{figure}
\includegraphics[width=16.67in]{../../img/R1_Increasing_q/Index} \caption{An example of the standardized biomass (blue) and the observed combined index (red) for R1, where an assumed 1 percent annual increase in catchability has not been accounted for in the standardization of the index.}\label{fig:r1-index}
\end{figure}

\hypertarget{r2.-hyperstable-indices-in-historical-period}{%
\subsection{R2. Hyperstable Indices in Historical Period}\label{r2.-hyperstable-indices-in-historical-period}}

The R2 Robustness test is identical to R1 (Figure \ref{fig:r1-compare}), except that the indices in the projection period are assumed to be proportional to the population; i.e., the 1\% increase in catchability that was not accounted for the in the standardization of the historical indices no longer occurs in the projection period.

\hypertarget{r3a-and-r3b.-effect-of-climate-change-on-recruitment-deviations-in-projection-period}{%
\subsection{R3a and R3b. Effect of Climate Change on Recruitment Deviations in Projection Period}\label{r3a-and-r3b.-effect-of-climate-change-on-recruitment-deviations-in-projection-period}}

Climate change is generally predicted to increase temperatures throughout the Atlantic Ocean, which could have significant effects on swordfish recruitment. The Atlantic Multidecadal Oscillation (AMO) is an indicator of long-duration changes in the sea surface temperature of the North Atlantic Ocean. Thus, it could serve as the basis for possible future patterns in recruitment. This is not postulating that the AMO is in fact driving swordfish recruitment. Rather it is using the 32-year time series as a representative of actual oceanographic conditions and one possible pattern of a cyclical productivity that we wish to test the robustness of a CMP. In essence, these robustness tests are asking whether the CMP is robust to an extended period (\textasciitilde15 years) of negative recruitment deviations without a change in the underlying productivity of the stock.

The entire AMO long time series (1856-present) was considered and a 32-year period (1980-2011) was selected to represent a time series that contained an extended period of consecutive negative and consecutive positive deviations. The AMO values multiplied by an implied annual inflation factor of 2.0 to simulate the hypothesis that climate change could result in larger recruitment deviations in the future than in the past.

Two versions of this approach were developed. R3a uses the AMO values directly, with a period of lower than average recruitment for the first fifteen years, followed by a period of higher than average deviations (Figure \ref{fig:r3} center panel). R3b considers the impact of just a period of negative recruitment deviations for the first fifteen years (Figure \ref{fig:r3} right panel).

In both cases (R3a and R3b), the climate-induced pattern in recruitment deviations is multiplied by the recruitment deviations from the reference model (R0; Figure \ref{fig:r3-2}).

\begin{figure}
\includegraphics[width=25in]{../../img/R3/RecDevs_mean} \caption{The cyclical (R3a) and initial negative pattern (R3b) in recruitment deviations for the robustness tests that investigate the impact of climate change on the performance of the CMPs. R0 is the reference model where no additional recruitment variabililty is added.}\label{fig:r3}
\end{figure}

\begin{figure}
\includegraphics[width=25in]{../../img/R3/RecDevs} \caption{An example of the recruitment deviations from three simulations. R0 is the reference model (OM 5 from the Reference Set). R3a superimposes a cyclical pattern in recruitment deviations over those from R0. R3b superimposes negative recruitment deviations over those from R0 for the first fifteen years, before reverting back to the recruitment pattern used in R0.}\label{fig:r3-2}
\end{figure}

\hypertarget{r4.-tac-implementation-error}{%
\subsection{R4. TAC Implementation Error}\label{r4.-tac-implementation-error}}

The R4 Robustness test evaluates the impact of a 10\% implementation error in the TAC. The catches are assumed to be 10\% higher than the TAC, but these catches are assumed to be unreported (i.e., the observed catches provided to the CMPs is equal to the TAC and \textasciitilde90\% of the actual landings).

\hypertarget{om-validation}{%
\section{OM Validation}\label{om-validation}}

\hypertarget{om-summary-report}{%
\subsection{OM Summary Report}\label{om-summary-report}}

A \href{../Reports/OM_Summary/2023/OM_Summary_Report.html}{Summary Report} summarizes the diagnostic checks, the calculated biological reference points, and the estimated stock status relative to those reference points, across the Reference and Robustness operating models.

\hypertarget{om-diagnostic-reports}{%
\subsection{OM Diagnostic Reports}\label{om-diagnostic-reports}}

Individual diagnostic reports with objective function values and plots of model fits and patterns in residuals are available for each of the Reference and Robustness OMs (and the 2022 assessment) on the North Atlantic Swordfish MSE \href{https://iccat.github.io/nswo-mse/}{homepage}.

\hypertarget{historical-spool-up-period}{%
\section{Historical Spool-Up Period}\label{historical-spool-up-period}}

The historical spool-up period was generated by importing the output from the SS3 assessment models and running the MSE simulation framework to recreate the historical fishery dynamics. No additional uncertainty was added to the historical simulations; that is, all \(50\) simulations were identical (e.g., same recruitment deviations) for the historical spool-up period.

The operating models have been conditioned on data up to and including 2020 (see the \protect\hyperlink{data}{Data section}), and therefore the projection period for the MSE framework starts in the following year, i.e., 2021. Currently, model uses assumed catches for the first three years (2021 - 2023) and then implements the management procedures in the following year (i.e., 2024). See the \protect\hyperlink{future-catches}{Future Catches} section for more information.

\hypertarget{historical-data}{%
\subsection{Historical Data}\label{historical-data}}

The observed fishery data was imported into the MSE framework and made available to the CMPs. Three sources of data available to the CMPs: 1) catch data, 2) a primary index of abundance, and 3) additional individual indices.

\hypertarget{catch-data}{%
\subsubsection{Catch Data}\label{catch-data}}

The catch data used in the OM conditioning are made available in the simulated data that is provided to the CMPs (Figure \ref{fig:catch-plot}).

\begin{figure}
\includegraphics[width=25in]{../../img/Catch_TAC} \caption{The historical total catch and total allowable catch (TAC) for the North Atlantic swordfish.}\label{fig:catch-plot}
\end{figure}

\hypertarget{indices-of-abundance}{%
\subsubsection{Indices of Abundance}\label{indices-of-abundance}}

\hypertarget{primary-index}{%
\paragraph{Primary Index}\label{primary-index}}

At the \href{../Meeting_Reports/2020_SWO_MSE_1_ENG.pdf}{2020 Swordfish MSE technical meeting (4 -- 5 June 2020)}, the Group chose to use the Combined Index (Ortiz et al., 2017) as the primary index for the development of CMPs. This index was updated for the 2022 assessment. The Combined Index was imported into the \texttt{SWOMSE} framework and made available to the CMPs (Figure \ref{fig:index-plot}).

\begin{figure}
\includegraphics[width=25in]{../../img/Combined_Index} \caption{The Combined Index for the North Atlantic swordfish fishery.}\label{fig:index-plot}
\end{figure}

\hypertarget{other-indices}{%
\paragraph{Other Indices}\label{other-indices}}

The additional individual fishery-dependent and survey indices are also imported into the MSE framework and made available to the CMPs (Figure \ref{fig:addindex-plot}).

\begin{figure}
\includegraphics[width=400px]{../../img/Individual_Indices} \caption{The additional individual fishery-dependent and survey indices for the North Atlantic swordfish fishery.}\label{fig:addindex-plot}
\end{figure}

\hypertarget{closed-loop-simulation-testing}{%
\section{Closed-Loop Simulation Testing}\label{closed-loop-simulation-testing}}

\hypertarget{simulation-specifications}{%
\subsection{Simulation Specifications}\label{simulation-specifications}}

The current simulation specifications for the MSE are:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Management interval: 3 (i.e., TAC updated every 3rd year)
\item
  Number of projection years: 33 (2021 -- 2053)
\item
  Number of simulations per OM: \(50\)
\end{enumerate}

\hypertarget{assumptions}{%
\subsection{Assumptions}\label{assumptions}}

\hypertarget{recruitment}{%
\subsubsection{Recruitment}\label{recruitment}}

The stock-recruitment relationship in the projection years was modeled using the Beverton-Holt function, with steepness fixed at the value assumed in the OM conditioning.

Recruitment deviations for the projection period were generated assuming a log-normal distribution with mean \(\mu_R\) and variance \(\sigma_R^2\), calculated as:

\[\mu_R = -0.5\sigma_R^2\left(1-\frac{\text{AC}}{\sqrt{(1-\text{AC}^2)}}\right)\]

where AC is the lag-1 autocorrelation factor calculated from the historical recruitment deviations and \(\sigma_R^2\) is the variance of the recruitment deviations specified in the OM (i.e., sigmaR\^{}2 defined \protect\hyperlink{om-conditioning}{above}).

The recruitment deviations for the projection period were generated independently for each simulation.

\hypertarget{life-history}{%
\subsubsection{Life-History}\label{life-history}}

Biological parameters such as mean weight-at-age and maturity-at-age were constant for all years (historical and projection).

\hypertarget{selectivity-1}{%
\subsubsection{Selectivity}\label{selectivity-1}}

Currently, the selectivity-at-length for the projection years is fixed to the estimated selectivity pattern from the last historical year for each OM. The reviewer of the \texttt{SWOMSE} R code highlighted this as a possible uncertainty and recommended that the Group consider testing alternative assumptions for the selectivity pattern in the projection years (Anon., 2021).

\begin{quote}
The Working Group will discuss this assumption in more detail and decide if it wishes to run scenarios with alternative assumptions for the selectivity pattern in the projection years.
\end{quote}

\hypertarget{catchability}{%
\subsubsection{Catchability}\label{catchability}}

No time-varying catchability is assumed for the projection years.

\hypertarget{future-catches}{%
\subsubsection{Future Catches}\label{future-catches}}

The total allowable catch (TAC) recommended by the CMPs is assumed to be implemented without error. That is, annual catches are equal to the TAC recommendations (provided sufficient vulnerable biomass was available). The Group determined that this assumption was appropriate based on the fact that historically the total landed catch has been below the total allowable catch (TAC) (see Figure \ref{fig:catch-plot}).

A Robustness Test (R4) has been designed to evaluate the consequences of violating this assumption.

The operating models also assume that the TACs recommended by the CMPs apply to the landed catch and do not include discards; that is, the actual removals will be higher than the TACs if there is discard mortality on the sub-legal fish.

The CMPs are first implemented in 2024, and every 3rd year after that, with the TAC held constant in the interim years. Since the MSE projection period begins in 2021 (the year after the conditioning), the landed catches for the first few projection years until the CMPS are implemented (2021, 2022, and 2023) are fixed and not set by the CMPs. The catch for 2021 is set at the reported level, and the catches for 2022 and 2023 are set to the mean from previous 10 years (2012 -- 2021) (Table \ref{tab:future-catches}).

\begin{table}

\caption{\label{tab:future-catches}The assumed landed catch (ton) for the first 3 projection years.}
\centering
\begin{tabu} to \linewidth {>{\raggedleft}X>{\raggedleft}X>{\raggedright}X}
\toprule
Year & Catch & Details\\
\midrule
2021 & 9729 & Reported Catch\\
2022 & 10770 & Assumed Catch\\
2023 & 10770 & Assumed Catch\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{generation-of-future-data}{%
\subsection{Generation of Future Data}\label{generation-of-future-data}}

\hypertarget{indices}{%
\subsubsection{Indices}\label{indices}}

The primary index of abundance (Combined Index) was generated in the projection years by adding observation error to the projected stock biomass, and standardizing to be on the same scale as the historical observed Combined Index.

The additional individual indices were generated in the projection years in the same manner, using the simulated stock biomass (or abundance in some cases).

The observation error was generated by calculating the statistical properties of the residuals from the fit of each respective index to the simulated stock (biomass or abundance) during the historical period. The procedure for calculating the residuals for the projection years is described in detail in the \href{https://openmse.com/features-conditioning-oms/indices/}{openMSE documentation}.

It was decided at the 2023 Intersessional Meeting of the Swordfish Working Group to calculate the statistical properties of the observation error for the Combined Index for the years 1999 -- 2020. This period was chosen as it includes only the years where the data used to generate the index included the majority of the fleets.

Following the assumptions of the stock assessment, it is assumed that all indices are proportional to the respective stock biomass or abundance (i.e., it is assumed that the indices are not hyper-stable or hyper-deplete). The only exception to this is \protect\hyperlink{R5}{Robustness Set 5} where the indices are assumed to have a 1\% annual average increase in catchability.

\hypertarget{catches}{%
\subsubsection{Catches}\label{catches}}

Following the assumption of the stock assessment, the observed catches in the projection years were generated with no observation error. That is, the observed catches in the MSE framework are equal to the actual simulated landed catches (provided there is sufficient biomass in the simulated population to support the prescribed TAC). The model does not include a bio-economic component and inter-annual change in fishing effort is unconstrained.

\hypertarget{data-lags}{%
\subsubsection{Data Lags}\label{data-lags}}

In the MSE framework, the CMPs are always provided with the simulated fishery data up to the previous year. That is, if a CMP is implemented in year \(t\), the catch and indices of abundance data provided to the CMP are up to and including year \(t-1\).

Data lags are then handled in the CMP code, where the default assumption is that the catch and index data are lagged by 2 years from the year where the TAC will be implemented; e.g., for setting the TAC for 2024, the data is up to and including 2022. See the CMP (see the \href{../cMPdevelopment/CMP-Development-Guide.html}{CMP Development Guide} for more details).

\hypertarget{interval}{%
\subsection{Management Interval}\label{interval}}

At the 2021 \href{/Meeting_Reports/2021_SWO_ENG.pdf}{Intersessional meeting}, the Group proposed a 3-year MP advice interval (see Table 5 in the \href{../Meeting_Reports//2021_SWO_ENG.pdf}{Report of the 2021 ICCAT Intersessional Meeting of the Swordfish Species Group}).

The operating models have been conditioned on data up to 2020. As described \protect\hyperlink{future-catches}{above}, the catches in 2021 -- 2023 are fixed to assumed values and the CMPs are first applied in 2024.

The 3-yr management interval is applied within the CMP code (see the \href{../cMPdevelopment/CMP-Development-Guide.html}{CMP Development Guide} for more details).

Robustness Set 9 (R9) evaluates the impact of alternative management intervals.

\hypertarget{performance-metrics}{%
\section{Performance Metrics}\label{performance-metrics}}

23 performance metrics (PMs) have been developed for the North Atlantic Swordfish MSE (Table \ref{tab:PM-Description}). These PMs are grouped into four families:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Status}: the probability the stock is in the green quadrant of the Kobe matrix
\item
  \textbf{Safety}: the probability of the stock not falling below the biological limit reference point
\item
  \textbf{Yield}: the TAC in the projection years (ton)
\item
  \textbf{Stability}: the variation in the TAC between management cycles
\end{enumerate}

\hypertarget{summary-of-performance-metrics}{%
\subsection{Summary of Performance Metrics}\label{summary-of-performance-metrics}}

The performance metrics are calculated over all the simulations (50) in each operating model. For example, \emph{PGK\_short} is calculated as the proportion of the 50 simulations where the spawning biomass (\(SB\)) is above \(SB_{MSY}\) and fishing mortality (\(F\)) is below \(F_{MSY}\).

The performance metrics can also be calculated over several operating models, for example the entire \protect\hyperlink{reference_models}{Reference Set}. This is done by first combining the MSE results for each OM (e.g., the 9 Reference OMs) into a single set of results (in this example, resulting in 450 simulations (9 OMs multiplied by 50 simulations per OM)), and then calculating the performance metrics over all results.

The Minimum Acceptable Performance values listed in Table \ref{tab:PM-Description} will be used as alternative values to determine if candidate management procedures meet the minimum performance criteria.

More details on the individual performance metrics are in the sections below.

\begin{table}

\caption{\label{tab:PM-Description}Summary of the North Atlantic Swordfish Performance Metrics.}
\centering
\begin{tabu} to \linewidth {>{}l>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\toprule
Family & Name & Description & Minimum Acceptable Values\\
\midrule
\textbf{Status} & PGK\_short & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 1-10 (2024-2033) & 51, 60, 70\\
\textbf{} & PGK\_med & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 11-20 (2034-2043) & 51, 60, 70\\
\textbf{} & PGK\_long & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 21-30 (2044-2053) & 51, 60, 70\\
\textbf{} & PGK & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) over all years (2024-2053) & 51, 60, 70\\
\textbf{} & PGK\_30 & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in year 30 (2053) & 51, 60, 70\\
\addlinespace
\textbf{} & POF & Probability of Overfishing (F>FMSY) over all years (2024-2053) & \\
\textbf{} & PNOF & Probability of Not Overfishing (F<FMSY) over all years (2024-2053) & \\
\textbf{Safety} & LRP\_short & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of the first 10 years (2024-2033) & 5, 10, 15\\
\textbf{} & LRP\_med & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of years 11-20 (2034-2043) & 5, 10, 15\\
\textbf{} & LRP\_long & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of years 21-30 (2044-2053) & 5, 10, 15\\
\addlinespace
\textbf{} & LRP & Probability of breaching the limit reference point (SB<0.4SBMSY) in any year (2024-2053) & 5, 10, 15\\
\textbf{Yield} & TAC1 & TAC (t) in the first implementation year (2024) & \\
\textbf{} & AvTAC\_short & Median TAC (t) over years 1-10 (2024-2033) & \\
\textbf{} & AvTAC\_med & Median TAC (t) over years 11-20 (2034-2043) & \\
\textbf{} & AvTAC\_long & Median TAC (t) over years 21-30 (2044-2053) & \\
\addlinespace
\textbf{Stability} & VarC & Mean variation in TAC (\%) between management cycles over all years and simulations & No minimum value and 25\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{peformance-metrics-examples}{%
\subsection{Peformance Metrics Examples}\label{peformance-metrics-examples}}

The following sections show figures and statistics for examples from each family of Performance Metrics. These results include two example candidate management procedures (MP1, MP2) (see \protect\hyperlink{CMPs}{Candidate Management Procedures}), with a single operating model that includes 10 stochastic simulations.

\hypertarget{summary-table}{%
\subsubsection{Summary Table}\label{summary-table}}

Table \ref{tab:PMtable} shows the summary performance statistics for the example CMPs. More details for each individual performance metric are in the sub-sections below.

\begin{table}

\caption{\label{tab:PMtable}Summary of Performance Metric values for some example CMPs.}
\centering
\begin{tabu} to \linewidth {>{}l>{\raggedright}X>{\raggedright}X>{\raggedleft}X>{\raggedleft}X}
\toprule
Family & Name & Description & MP1 & MP2\\
\midrule
\textbf{Status} & PGK\_short & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 1-10 (2024-2033) & 0.06 & 0.31\\
\textbf{} & PGK\_med & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 11-20 (2034-2043) & 0.15 & 0.58\\
\textbf{} & PGK\_long & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in years 21-30 (2044-2053) & 0.16 & 0.66\\
\textbf{} & PGK & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) over all years (2024-2053) & 0.12 & 0.52\\
\textbf{} & PGK\_30 & Probability of being in Green Zone of Kobe Space (SB>SBMSY \& F<FMSY) in year 30 (2053) & 0.10 & 0.80\\
\addlinespace
\textbf{} & POF & Probability of Overfishing (F>FMSY) over all years (2024-2053) & 0.65 & 0.27\\
\textbf{Safety} & LRP\_short & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of the first 10 years (2024-2033) & 0.00 & 0.00\\
\textbf{} & LRP\_med & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of years 11-20 (2034-2043) & 0.30 & 0.10\\
\textbf{} & LRP\_long & Probability of breaching the limit reference point (SB<0.4SBMSY) in any of years 21-30 (2044-2053) & 0.30 & 0.10\\
\textbf{} & LRP & Probability of breaching the limit reference point (SB<0.4SBMSY) in any year (2024-2053) & 0.30 & 0.10\\
\addlinespace
\textbf{Yield} & TAC1 & TAC (t) in the first implementation year (2024) & 13462.50 & 11987.02\\
\textbf{} & AvTAC\_short & Median TAC (t) over years 1-10 (2024-2033) & 13097.11 & 11201.15\\
\textbf{} & AvTAC\_med & Median TAC (t) over years 11-20 (2034-2043) & 10332.16 & 10200.13\\
\textbf{} & AvTAC\_long & Median TAC (t) over years 21-30 (2044-2053) & 9883.48 & 8793.29\\
\textbf{Stability} & VarC & Mean variation in TAC (\%) between management cycles over all years and simulations & 0.15 & 0.14\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{status}{%
\subsection{Status}\label{status}}

\hypertarget{pgk_short}{%
\subsubsection{PGK\_short}\label{pgk_short}}

\texttt{PGK\_short} calculates the probability of being in Green Zone of Kobe Space (SB\textgreater SBMSY \& F\textless FMSY) in years 1-10 (2024-2033). This is calculated as the proportion of the total number of simulations that are in the Green Zone of Kobe Space in those years.

Figure \ref{fig:PGKshort} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{PGK\_short} in this example are: 0.06, 0.31.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/PGK_short} \caption{An example of time-series plots of F/FMSY and SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>SBMSY and F<FMSY in 2033 are indicated with a green point, and those outside of the green space in the Kobe plot are indicated in red. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:PGKshort}
\end{figure}

\hypertarget{pgk_med}{%
\subsubsection{PGK\_med}\label{pgk_med}}

\texttt{PGK\_med} calculates the probability of being in Green Zone of Kobe Space (SB\textgreater SBMSY \& F\textless FMSY) over years 11--20 (2034--2043). This is calculated as the proportion of the total points (number of simulations x number of years) that are in the Green Zone of Kobe Space.

Figure \ref{fig:PGKmed} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{PGK\_med} in this example are: 0.15, 0.58.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/PGK_med} \caption{An example of time-series plots of F/FMSY and SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>SBMSY and F<FMSY in years 2029--2033 are indicated with a green point, and those outside of the green space in the Kobe plot are indicated in red. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:PGKmed}
\end{figure}

\hypertarget{pgk_long}{%
\subsubsection{PGK\_long}\label{pgk_long}}

\texttt{PGK\_long} calculates the probability of being in Green Zone of Kobe Space (SB\textgreater SBMSY \& F\textless FMSY) over years 21--30 (2044--2053). This is calculated as the proportion of the total points (number of simulations x number of years) that are in the Green Zone of Kobe Space.

Figure \ref{fig:PGKlong} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{PGK\_long} in this example are: 0.16, 0.66.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/PGK_long} \caption{An example of time-series plots of F/FMSY and SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>SBMSY and F<FMSY in years 2034--2053 are indicated with a green point, and those outside of the green space in the Kobe plot are indicated in red. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:PGKlong}
\end{figure}

\hypertarget{pgk}{%
\subsubsection{PGK}\label{pgk}}

\texttt{PGK} calculates the probability of being in Green Zone of Kobe Space (SB\textgreater SBMSY \& F\textless FMSY) over all years (2024--2053). This is calculated as the proportion of the total points (number of simulations x number of years) that are in the Green Zone of Kobe Space.

Figure \ref{fig:PGK} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{PGK} in this example are: 0.12, 0.52.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/PGK} \caption{An example of time-series plots of F/FMSY and SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>SBMSY and F<FMSY are indicated with a green point, and those outside of the green space in the Kobe plot are indicated in red. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:PGK}
\end{figure}

\hypertarget{pgk_30}{%
\subsubsection{PGK\_30}\label{pgk_30}}

\texttt{PGK\_30} calculates the probability of being in Green Zone of Kobe Space (SB\textgreater SBMSY \& F\textless FMSY) in year (2053). This is calculated as the proportion of the total number of simulations that are in the Green Zone of Kobe Space.

Figure \ref{fig:PGK30} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{PGK\_30} in this example are: 0.1, 0.8.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/PGK_30} \caption{An example of time-series plots of F/FMSY and SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>SBMSY and F<FMSY in 2053 are indicated with a green point, and those outside of the green space in the Kobe plot are indicated in red. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:PGK30}
\end{figure}

\hypertarget{pof-and-pnof}{%
\subsubsection{POF and PNOF}\label{pof-and-pnof}}

\texttt{POF} calculates the probability of over-fishing (F\textgreater FMSY) over all years (2024--2053). This is calculated as the proportion of the total number of points (number of simulations x number of years) where F is greater than FMSY.

Figure \ref{fig:POF} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{POF} in this example are: 0.65, 0.27.

\texttt{PNOF} reports the probability of not overfishing, calculated as \(1-\text{POF}\), i.e.~0.35, 0.73.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/POF} \caption{An example of a time-series plot of F/FMSY for a two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where F<FMSY are indicated with a green point, and red points indicate F>FMSY. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:POF}
\end{figure}

\hypertarget{safety}{%
\subsection{Safety}\label{safety}}

\hypertarget{lrp_short}{%
\subsubsection{LRP\_short}\label{lrp_short}}

\texttt{LRP\_short} calculates the probability of breaching the limit reference point (LRP; SB\textless0.4SBMSY) in any of the first 10 years (2024-2033).

This is calculated as the proportion of simulations where SB\textless0.4SBMSY in any of the first 10 years.

Figure \ref{fig:LRPshort} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{LRP\_short} in this example are: 0, 0.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/LRP_short} \caption{An example of a time-series plot of SB/SBMSY for a two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>0.4SBMSY are indicated with a green point, and red points indicate SB<0.4SBMSY. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:LRPshort}
\end{figure}

\hypertarget{lrp_med}{%
\subsubsection{LRP\_med}\label{lrp_med}}

\texttt{LRP\_med} calculates the probability of breaching the limit reference point (LRP; SB\textless0.4SBMSY) in any of years 11-20 (2034-2043).

This is calculated as the proportion of simulations where SB\textless0.4SBMSY in any of years 11-20.

Figure \ref{fig:LRP-med} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{LRP\_med} in this example are: 0.3, 0.1.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/LRP_med} \caption{An example of a time-series plot of SB/SBMSY for a two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>0.4SBMSY are indicated with a green point, and red points indicate SB<0.4SBMSY. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:LRP-med}
\end{figure}

\hypertarget{lrp_long}{%
\subsubsection{LRP\_long}\label{lrp_long}}

\texttt{LRP\_long} calculates the probability of breaching the limit reference point (LRP; SB\textless0.4SBMSY) in any of years 21-30 (2044-2053).

This is calculated as the proportion of simulations where SB\textless0.4SBMSY in any of the last 10 years.

Figure \ref{fig:LRP-long} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The value for \texttt{LRP\_long} in this example are: 0.3, 0.1.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/LRP_long} \caption{An example of a time-series plot of SB/SBMSY for two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>0.4SBMSY are indicated with a green point, and red points indicate SB<0.4SBMSY. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:LRP-long}
\end{figure}

\hypertarget{lrp}{%
\subsubsection{LRP}\label{lrp}}

\texttt{LRP} calculates the probability of breaching the limit reference point (LRP; SB\textless0.4SBMSY) in any of the projection years (2024-2053).

This is calculated as the proportion of simulations where SB\textless0.4SBMSY in any year.

Figure \ref{fig:LRP} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The value for \texttt{LRP} in this example are: 0.3, 0.1.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/LRP} \caption{An example of a time-series plot of SB/SBMSY for a two CMPs. This OM has 10 simulations, shown as the colored lines. Simulations where SB>0.4SBMSY are indicated with a green point, and red points indicate SB<0.4SBMSY. The Kobe plot on the bottom shows these points in the Kobe space. The numbers in the corners indicate the percent of points in each area of the Kobe space.}\label{fig:LRP}
\end{figure}

\hypertarget{yield}{%
\subsection{Yield}\label{yield}}

\hypertarget{tac1}{%
\subsubsection{TAC1}\label{tac1}}

\texttt{TAC1} calculates the median TAC (t) in the first year (2024). This is calculated as the median across the simulations of the 2024 TAC.

Figure \ref{fig:C1} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{TAC1} in this example are: 13462, 11987.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/C1} \caption{An example of time-series plots of the TAC for two CMPs. This OM has 10 simulations, shown as the colored lines. The points indicate the values used to calculate the median value.}\label{fig:C1}
\end{figure}

\hypertarget{avtac_short}{%
\subsubsection{AvTAC\_short}\label{avtac_short}}

\texttt{AvTAC\_short} calculates the median TAC (t) in the first 10 years (2024--2033). This is calculated as the median TAC across the simulations and years.

Figure \ref{fig:AvC10} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{AvTAC\_short} in this example are: 13097, 11201.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/AvTAC_short} \caption{An example of time-series plots of the TAC for a two CMPs. This OM has 10 simulations, shown as the colored lines. The points indicate the values used to calculate the median value.}\label{fig:AvC10}
\end{figure}

\hypertarget{avtac_med}{%
\subsubsection{AvTAC\_med}\label{avtac_med}}

\texttt{AvTAC\_med} calculates the median TAC (t) in years 11 -- 20 (2034--2043). This is calculated as the median TAC across the simulations and years.

Figure \ref{fig:AvCmed} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{AvTAC\_med} in this example are: 10332, 10200.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/AvTAC_med} \caption{An example of time-series plots of the TAC for a two CMPs. This OM has 10 simulations, shown as the colored lines. The points indicate the values used to calculate the median value.}\label{fig:AvCmed}
\end{figure}

\hypertarget{avtac_long}{%
\subsubsection{AvTAC\_long}\label{avtac_long}}

\texttt{AvTAC\_long} calculates the median TAC (t) in the last 10 years (2044--2053). This is calculated as the median TAC across the simulations and years.

Figure \ref{fig:AvC30} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{AvTAC\_long} in this example are: 9883, 8793.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/AvTAC_long} \caption{An example of time-series plots of the TAC for a two CMPs. This OM has 10 simulations, shown as the colored lines. The points indicate the values used to calculate the median value.}\label{fig:AvC30}
\end{figure}

\hypertarget{stability}{%
\subsection{Stability}\label{stability}}

\hypertarget{varc}{%
\subsubsection{VarC}\label{varc}}

\texttt{VarC} calculates the mean absolute change in the TAC between management cycles, calculated across all years and simulations.

Figure \ref{fig:VarC} shows an example of two CMPs (MP1, MP2) for an operating model with 10 simulations. The values for \texttt{VarC} in this example are: 0.15, 0.14.

\begin{figure}
\includegraphics[width=400px]{../../img/PMs/VarC} \caption{Violin plots of the relative absolute change in the TAC between management cycles for two CMPs.}\label{fig:VarC}
\end{figure}

\hypertarget{CMPs}{%
\section{Candidate Management Procedures}\label{CMPs}}

\hypertarget{tuning}{%
\subsection{Tuning of Candidate Management Procedures}\label{tuning}}

During development, the Candidate Management Procedures are tuned to achieve specific performance outcomes. These performance outcomes are calculated across all the Reference OMs; i.e, the MSE results from each Reference OM are aggregated together. 3 different tuning targets have been specified (Table \ref{tab:PM-tuning}).

There will be 3 versions of each CMP corresponding to metrics and targets described in Table \ref{tab:PM-tuning}. The names of the CMPs include the tuning code (i.e., `a', `b').

\begin{table}

\caption{\label{tab:PM-tuning}The codes, metrics, and targets used for the tuning of the CMPs.}
\centering
\begin{tabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedleft}X}
\toprule
Code & Metric & Target\\
\midrule
a & PGK short & 0.51\\
b & PGK short & 0.60\\
c & PGK short & 0.70\\
\bottomrule
\end{tabu}
\end{table}

\hypertarget{reporting-of-mse-results}{%
\section{Reporting of MSE Results}\label{reporting-of-mse-results}}

\hypertarget{interactive-application}{%
\subsection{Interactive Application}\label{interactive-application}}

The current MSE results are available in an \href{https://shiny.bluematterscience.com/app/swomse}{Interactive Application}

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-anon.Report2017ICCAT2017}{}}%
Anon. (2017). Report of the 2017 {ICCAT Atlantic Swordfish Stock Assessment Session}. {SCRS}/2017/008. \emph{Collect. Vol. Sci. Pap. ICCAT}, \emph{74}(3), 841--967. \url{https://www.iccat.int/Documents/CVSP/CV074_2017/n_3/CV074030841.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-anon.PeerReviewNorth2021}{}}%
Anon. (2021). Peer review of the {North Atlantic Swordfish Management Strategy Evaluation} ({MSE}) code and algorithms {SCRS}/2021/097. \emph{Collect. Vol. Sci. Pap. ICCAT,} \emph{78}(7).

\leavevmode\vadjust pre{\hypertarget{ref-carruthersDataLimitedMethodsToolkit2018}{}}%
Carruthers, T., \& Hordyk, A. R. (2018). The {Data-Limited Methods Toolkit} ({DLMtool}): {An R} package for informing management of data-limited populations. \emph{Methods in Ecology and Evolution}, \emph{9}(12), 2388--2395. \url{https://doi.org/10.1111/2041-210X.13081}

\leavevmode\vadjust pre{\hypertarget{ref-francisDataWeightingStatistical2011}{}}%
Francis, R. I. C. C. (2011). Data weighting in statistical fisheries stock assessment models. \emph{Canadian Journal of Fisheries and Aquatic Sciences}, \emph{68}(6), 1124--1138. \url{https://doi.org/10.1139/f2011-025}

\leavevmode\vadjust pre{\hypertarget{ref-methotStockSynthesisBiological2013}{}}%
Methot, R. D., \& Wetzel, C. R. (2013). Stock synthesis: {A} biological and statistical framework for fish stock assessment and fishery management. \emph{Fisheries Research}, \emph{142}, 86--99. \url{https://doi.org/10.1016/j.fishres.2012.10.012}

\leavevmode\vadjust pre{\hypertarget{ref-ortizUpdatedCombinedBiomass2017}{}}%
Ortiz, M., Mejuto, J., Hanke, A., Ijima, H., Walter, J., Coelho, R., \& Ikkiss, A. (2017). Updated combined biomass index of abundance of {North Atlantic} swordfish stock 1963 - 2015. {SCRS}/2017/137. \emph{Collect. Vol. Sci. Pap. ICCAT}, \emph{74}(3), 1275--1294. \url{https://www.iccat.int/Documents/CVSP/CV074_2017/n_3/CV074031275.pdf}

\end{CSLReferences}

\end{document}
